<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
	"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
  <head>
    <title>WPI Lens and Lights</title>

    <link rel="stylesheet" type="text/css" href="main.css" />
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <meta name="author" content="Lens and Lights" />
    <meta name="Copyright" content="Copyright (c) WPI Lens and Lights 2006" />

    <link rel="stylesheet" href="css/lightbox.css" type="text/css" media="screen" />
    <script src="js/prototype.js" type="text/javascript"></script>
    <script src="js/scriptaculous.js?load=effects" type="text/javascript"></script>
    <script src="js/lightbox.js" type="text/javascript"></script>

     <!-- Special IE-only comment to load a special CSS file for IE -->
     <!--[if IE]>
     <link rel="stylesheet" type="text/css" href="ie.css" />
     <![endif]-->

	
  </head>
  <body>
    <div id="hdrimg">
      <h1><a href=""><img src="images/logo.gif"/></a></h1>
      <ul id="nav">      
        <li><a href="index.html" title=""<!--#if expr="$section = home" --> id="current" <!--#endif -->>home</a></li>
		<li><a href="workorder.html" title=""<!--#if expr="$section = workorder" --> id="current" <!--#endif -->>workorder</a></li>
        <li><a href="sound.html" title=""<!--#if expr="$section = sound" --> id="current" <!--#endif -->>sound</a></li>
        <li><a href="lighting.html" title=""<!--#if expr="$section = lighting" --> id="current" <!--#endif -->>lighting</a></li>
        <li><a href="projection.html" title=""<!--#if expr="$section = projection" --> id="current" <!--#endif -->>projection</a></li>
        <li><a href="pictures.html" title=""<!--#if expr="$section = pictures" --> id="current" <!--#endif -->>pictures</a></li>
        <li><a href="members.html" title=""<!--#if expr="$section = members" --> id="current" <!--#endif -->>members</a></li>
        <li><a href="about.html" title=""<!--#if expr="$section = about" --> id="current" <!--#endif -->>about</a></li>
        <li><a href="contact.html" title=""<!--#if expr="$section = contact" --> id="current" <!--#endif -->>contact</a></li>

      </ul>
    </div>
    <div class="rowcontainer">
